### ISSUE TITLE
tracking nx issues

### ISSUE THREAD

**Issue by Hotell** [productboardlabs/multioss#1]
> Please add here any issues/features missing that you ran into/have reported. thx!

## Bugs

- [ ] https://github.com/nrwl/nx/issues/2188
- [ ] https://github.com/nrwl/nx/issues/2119
- [ ] https://github.com/nrwl/nx/issues/1881
- [x] https://github.com/nrwl/nx/issues/2240
- [ ] https://github.com/nrwl/nx/issues/2267
- [x] https://github.com/nrwl/nx/issues/2317
- [ ] jest and setupFiles https://github.com/nrwl/nx/issues/2344
- [x] jest config https://github.com/nrwl/nx/issues/2345

## Missing Features

- [ ] making existing library publishable https://github.com/nrwl/nx/issues/2329
- [ ] estlint cache https://github.com/nrwl/nx/issues/2337
- [ ] public facing types/apis https://github.com/nrwl/nx/issues/2310
- [ ] workspace docs https://github.com/nrwl/nx/issues/2299
- [x] set memory limit to TsForkChecker https://github.com/nrwl/nx/issues/2272
- [x] vanilla node libraries builder https://github.com/nrwl/nx/issues/2189
- [x] babel-jest https://github.com/nrwl/nx/issues/1720
- [x] CSS modules https://github.com/nrwl/nx/issues/1744
- [x] support vanilla javascript https://github.com/nrwl/nx/pull/2247
- [x] Svg as Component/asset https://github.com/nrwl/nx/pull/1964
- [x] Img loading https://github.com/nrwl/nx/pull/2245
- [x] Vanilla js files support https://github.com/nrwl/nx/pull/2247
  - ~issues https://github.com/nrwl/nx/pull/2247#pullrequestreview-337704714~

### Dep Graph
- [ ] include vendor within the graph https://github.com/nrwl/nx/issues/1796

### Storybook
- [x]  react component schematics generation/e2e specs  https://github.com/nrwl/nx/issues/2658
- [x]  adding wrong deps https://github.com/nrwl/nx/issues/2630
- [ ] importing other workspace libs within story https://github.com/nrwl/nx/issues/2320

### Pipeline (affected)
- [ ] libs build https://github.com/nrwl/nx/issues/2671

**Bugs**
- [ ] https://github.com/nrwl/nx/issues/2720
- [ ] https://github.com/nrwl/nx/issues/2721

## Future/Questions 

- TS: leveraging composite projects/incremental build
- other languages support 
- react native
- custom builder schematics + runner (eg: `nx workspace-schematic`)
- custom scripts schematics + runner
- custom lint schematics + runner
- tweaking file (names/contents) from existing schematic plugins
- changelogs automation with semver (semver for publishable packages)
